from typing import Any


def telegram_local_commands() -> list[dict[str, Any]]:
    return [
        {
            "command": "start",
            "title": "🏛️ Avvia Hestia",
            "description": "Avvia Hestia",
            "method": "POST",
            "path": "/local/start",
            "clients": ["telegram", "ui"],
            "response_mode": "telegram_local",
            "telegram_visible": True,
            "telegram_menu_visible": False,
            "telegram_help_visible": False,
        },
        {
            "command": "help",
            "title": "📘 Guida e comandi",
            "description": "Mostra guida e comandi",
            "method": "POST",
            "path": "/local/help",
            "clients": ["telegram", "ui"],
            "response_mode": "telegram_local",
            "telegram_visible": True,
            "telegram_menu_visible": False,
            "telegram_help_visible": False,
        },
        {
            "command": "clear",
            "title": "🧹 Pulisci memoria chat",
            "description": "Cancella sessione e memoria chat",
            "method": "POST",
            "path": "/local/clear",
            "clients": ["telegram", "ui"],
            "response_mode": "telegram_local",
            "telegram_visible": True,
            "telegram_menu_visible": False,
            "telegram_help_visible": False,
        },
        {
            "command": "set",
            "title": "⚙️ Imposta parametro sessione",
            "description": "Imposta un parametro sessione (es. tone, custom_prompt)",
            "method": "POST",
            "path": "/local/set",
            "clients": ["telegram", "ui"],
            "response_mode": "telegram_local",
            "telegram_visible": True,
            "telegram_menu_visible": False,
            "telegram_help_visible": False,
            "arguments_help": "<parametro>",
        },
        {
            "command": "settings",
            "title": "🧾 Vedi impostazioni sessione",
            "description": "Mostra impostazioni sessione attive",
            "method": "POST",
            "path": "/local/settings",
            "clients": ["telegram", "ui"],
            "response_mode": "telegram_local",
            "telegram_visible": True,
            "telegram_menu_visible": False,
            "telegram_help_visible": False,
        },
        {
            "command": "reset_settings",
            "title": "♻️ Reset impostazioni sessione",
            "description": "Resetta impostazioni sessione",
            "method": "POST",
            "path": "/local/reset_settings",
            "clients": ["telegram", "ui"],
            "response_mode": "telegram_local",
            "telegram_visible": True,
            "telegram_menu_visible": False,
            "telegram_help_visible": False,
        },
        {
            "command": "notifica_add",
            "title": "➕ Aggiungi notifica",
            "description": "Crea una notifica in modo assistito",
            "method": "POST",
            "path": "/local/notifica_add",
            "clients": ["telegram", "ui"],
            "response_mode": "telegram_local",
            "telegram_visible": True,
            "telegram_menu_visible": True,
            "telegram_help_visible": True,
        },
        {
            "command": "notifica_get",
            "title": "📋 Notifiche attive",
            "description": "Mostra notifiche attive",
            "method": "POST",
            "path": "/local/notifica_get",
            "clients": ["telegram", "ui"],
            "response_mode": "telegram_local",
            "telegram_visible": True,
            "telegram_menu_visible": True,
            "telegram_help_visible": True,
        },
        {
            "command": "notifica_remove",
            "title": "➖ Rimuovi notifica",
            "description": "Disattiva una notifica",
            "method": "POST",
            "path": "/local/notifica_remove",
            "clients": ["telegram", "ui"],
            "response_mode": "telegram_local",
            "telegram_visible": True,
            "telegram_menu_visible": True,
            "telegram_help_visible": True,
            "arguments_help": "subscription_id=<id>",
        },
        {
            "command": "create_event",
            "title": "📅 Crea evento",
            "description": "Crea un nuovo evento nel calendario in modo assistito",
            "method": "POST",
            "path": "/local/create_event",
            "clients": ["telegram", "ui"],
            "response_mode": "telegram_local",
            "telegram_visible": True,
            "telegram_menu_visible": True,
            "telegram_help_visible": True,
        },
        {
            "command": "create_task",
            "title": "✅ Crea task",
            "description": "Crea un nuovo task o attività in modo assistito",
            "method": "POST",
            "path": "/local/create_task",
            "clients": ["telegram", "ui"],
            "response_mode": "telegram_local",
            "telegram_visible": True,
            "telegram_menu_visible": True,
            "telegram_help_visible": True,
        },
        {
            "command": "create_reminder",
            "title": "⏰ Crea promemoria",
            "description": "Crea un nuovo promemoria in modo assistito",
            "method": "POST",
            "path": "/local/create_reminder",
            "clients": ["telegram", "ui"],
            "response_mode": "telegram_local",
            "telegram_visible": True,
            "telegram_menu_visible": True,
            "telegram_help_visible": True,
        },
        {
            "command": "documents",
            "title": "📎 Documenti salvati",
            "description": "Visualizza i documenti caricati e archiviati con embeddings",
            "method": "POST",
            "path": "/local/documents",
            "clients": ["telegram", "ui"],
            "response_mode": "telegram_local",
            "telegram_visible": True,
            "telegram_menu_visible": True,
            "telegram_help_visible": True,
        },
    ]
