services:
  chronos:
    build: .
    container_name: hestia_chronos
    restart: unless-stopped
    ports:
      - "19007:19007"
    env_file:
      - ./app/.env
    environment:
      - HUB_API_URL=http://hestia_hub:19001/api
      - CALENDAR_SERVICE_BASE_URL=http://hestia_chronos:19007
      - CALENDAR_PORT=19007
      - PYTHONUNBUFFERED=1
    networks:
      - hestia_net

networks:
  hestia_net:
    external: true
